version: '3.0'
services:
  chronicle:
    network_mode: host
    build: 
      context: ./chronicle
    volumes:
      - ./chronicle:/opt/data
    environment:
      - DATA_DIR=./data
      - MODE=scan
      - HOST=mainnet.telosusa.io #ip address or hostname of nodeos with state-history plogin
      - PORT=8890 #port number of state history plugin
      - WS_HOST=localhost # ip address or hostname json's consumer
      - WS_PORT=8800 # port number of json's consumer
      - SKIP_BLOCK_EVENTS=false
      - SKIP_TABLE_DELTAS=false
      - SKIP_TRACES=false
      - BIN_HEADER=true
      - EXP_WS_PATH=/
      - EXP_WS_MAX_QEUEU=10000
      - IRREVERSIBLE_ONLY=false
      - START_BLOCK=71468981
      - STALE_DEADLINE=20000
